language: python
sudo: required
branches:
  only:
  - master
  - "/^[0-9]+\\.[0-9]+\\.[0-9]+/"
python: 3.6
matrix:
  include:
  - python: "2.7"
    env: TOXENV=py27
  - python: "3.3"
    env: TOXENV=py33
  - python: "3.4"
    env: TOXENV=py34
  - python: "3.5"
    env: TOXENV=py35
  - python: "3.6"
    env: TOXENV=py36
  - python: "3.6"
    env: TOXENV=flake8
install:
- pip install tox codecov
script:
- tox
after_success:
- codecov
deploy:
  provider: pypi
  user: a04316
  password:
    secure: uzzRlbSxHSIz1TwCAcRsmNq9wYhAY7wwfcCzlDydbFG9AaF3c845p42BPCRKxbzNIZDvzj3EwLh/rV2mbeO40oF9UoZaZOte6Ew7ruW5EjbWBNTcuLWBXPeBJLpuUmbX6ywXUVvxzhbxXoob+OdSrITvqjNb2r5QTphKjIifrs1QcLI05qsaqgTGgCyHAlrXYH3NCdbRCvp3985wxOFC0RXP69fuvw3pVqMDV/Uokdb3w9NI0WgieBRlJU21FT3Y07Fa7ieqOylkxQx14YzncharLprUHGzOOU8ZbJfQKcxrs7ugxlgHwc3XbnPa469XIx2g0AbaIyrAhPYjvoEHBxcgnPFUfTU+oSVoe23OLwVCyfYd6g6/1GkPQdBQuOUKKZIRR0y+0c9PKuO9YoX3KFNUsmttWBRiStXek29m0vVM+00GAXFAAl3w+kw62U0GvumEMPUx3ivRx167QrH0Z/67x/PHFM7fGLFbtA3sWkf8qLyb15uWp520OKCIFfjO9yfrN7WQRoJMMklyDtm5dl5+chDeSbE1g1ZxWNVvIfzpBYYcgi0/FnjHvpUm3nSIkSa+HIedyD034HY/L25JwUaslOGhmRZpVCpoTCbJpMb4ueyxGESrZo9kg6xIPzFBtxdCtAZFdOvV4YgyTnqxY7IpmZD0tRUQB/E0RKyqZMo=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: s-fujimoto/sshec2
    condition: "$TOXENV = py36"
notifications:
  slack:
    secure: MulHsfP0ab6Oz4PaFx/6hVuoE/zpVDtFCZY7lpGITPkDu4+uP8R9Dhz/UwxpYA2JTIDuWeJ8kZkTQbEUxfEFAvPAKvMLL6YpnnOrXCummpeFQRXFxMCxP8ilaIeCgOYQSxVB9eQMoyoNdvQmxiN/+c8vi8QVrS/VIb4OGjRYy0P0dvwzEn2cwbEokCSF0GwIt26DuxdiO/vx389+YDCdTs0+ViE//sxtvSbhbyaFKHUYax/5Z//jFxxUcAdbSYqPrcHPeJCfkGedeyto42oAR0B3tgeq0FKYR9605LtPqWrJj8k03ZGy5Jl3Hrs/G9bZk+o1XzZtX+rlIQZKGJ2PMZtnblDuZFxet8om0i1U2tSUiRC/d2NWbJ9jbuWXlcrxkqmcygEuI/g/Pn2CBeW7XhnHXmwdqxmJyVddzTpVr9Tv04aQUsLGsYHkpbVBtuREDr09CBgIeQ7nxE758moxTt0StzARN8KvWlKLwF3Tnx8m7b8eTVNZdtDWjXQ9+mgIu4wKiSx5maQ8eyYoNrFXbH3TuV9iAX2ahnoOueqnyDufKtkVH/+KEQVj3JtsK0oC3jUKnIz9C8ZFnTiOmQ3AiTW6NEswPcJY+exrskWGr7OS/gQKHLrQTYfe2t2OE3376TCv5fTNNyNF1987nsWtG51KhTYcmZscuCFMbioMsFY=
